# fly.toml app configuration file for tcg-tracker

app = 'tcg-tracker'
primary_region = 'scl'

[build]
  dockerfile = "Dockerfile"
  target = "release"

# THIS IS THE CRUCIAL SECTION THAT IS LIKELY MISSING OR INCORRECT
[deploy]
  release_command = "flask db upgrade"
  vm_memory = "512mb" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  FLASK_ENV = "production"

[[processes]]
  name = "app"
  cmd = ["gunicorn", "--bind", ":8080", "--workers", "1", "app:app"]
  
  [processes.vm]
    memory = '1gb'
    cpu_kind = 'shared'
    cpus = 1

[[processes]]
  name = "cron"
  schedule = "0 8 * * *"
  
  [processes.build]
    dockerfile = "Dockerfile"
    target = "cron_release"

  [processes.vm]
    size = "shared-cpu-1x-256mb"