"""empty message

Revision ID: 1ec50e376fbe
Revises: 2ee318a20bcc
Create Date: 2025-07-15 14:47:50.109224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec50e376fbe'
down_revision = '2ee318a20bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('deck_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'deck_url')
    # ### end Alembic commands ###
