"""add_opponent_commander_in_match_table_and_update_logged_match

Revision ID: 2ee318a20bcc
Revises: cd5a1428ef55
Create Date: 2025-06-05 10:31:37.400868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee318a20bcc'
down_revision = 'cd5a1428ef55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('opponent_commanders_in_match',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logged_match_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.Column('commander_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.CheckConstraint('seat_number >= 1 AND seat_number <= 4', name='check_ocim_seat_number'),
    sa.ForeignKeyConstraint(['commander_id'], ['commanders.id'], ),
    sa.ForeignKeyConstraint(['logged_match_id'], ['logged_matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opponent_commanders_in_match_commander_id'), 'opponent_commanders_in_match', ['commander_id'], unique=False)
    op.create_index(op.f('ix_opponent_commanders_in_match_logged_match_id'), 'opponent_commanders_in_match', ['logged_match_id'], unique=False)
    op.create_index(op.f('ix_opponent_commanders_in_match_role'), 'opponent_commanders_in_match', ['role'], unique=False)
    op.create_index(op.f('ix_opponent_commanders_in_match_seat_number'), 'opponent_commanders_in_match', ['seat_number'], unique=False)
    op.drop_constraint('logged_matches_commander_at_seat1_id_fkey', 'logged_matches', type_='foreignkey')
    op.drop_constraint('logged_matches_commander_at_seat4_id_fkey', 'logged_matches', type_='foreignkey')
    op.drop_constraint('logged_matches_commander_at_seat2_id_fkey', 'logged_matches', type_='foreignkey')
    op.drop_constraint('logged_matches_commander_at_seat3_id_fkey', 'logged_matches', type_='foreignkey')
    op.drop_column('logged_matches', 'commander_at_seat3_id')
    op.drop_column('logged_matches', 'commander_at_seat1_id')
    op.drop_column('logged_matches', 'commander_at_seat2_id')
    op.drop_column('logged_matches', 'commander_at_seat4_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('commander_at_seat4_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('commander_at_seat2_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('commander_at_seat1_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('commander_at_seat3_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('logged_matches_commander_at_seat3_id_fkey', 'logged_matches', 'commanders', ['commander_at_seat3_id'], ['id'])
    op.create_foreign_key('logged_matches_commander_at_seat2_id_fkey', 'logged_matches', 'commanders', ['commander_at_seat2_id'], ['id'])
    op.create_foreign_key('logged_matches_commander_at_seat4_id_fkey', 'logged_matches', 'commanders', ['commander_at_seat4_id'], ['id'])
    op.create_foreign_key('logged_matches_commander_at_seat1_id_fkey', 'logged_matches', 'commanders', ['commander_at_seat1_id'], ['id'])
    op.drop_index(op.f('ix_opponent_commanders_in_match_seat_number'), table_name='opponent_commanders_in_match')
    op.drop_index(op.f('ix_opponent_commanders_in_match_role'), table_name='opponent_commanders_in_match')
    op.drop_index(op.f('ix_opponent_commanders_in_match_logged_match_id'), table_name='opponent_commanders_in_match')
    op.drop_index(op.f('ix_opponent_commanders_in_match_commander_id'), table_name='opponent_commanders_in_match')
    op.drop_table('opponent_commanders_in_match')
    # ### end Alembic commands ###
