"""Added time_lord_doctor column

Revision ID: 3e34bb0d2f8f
Revises: 9153e76b1d55
Create Date: 2025-03-20 11:41:36.820238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e34bb0d2f8f'
down_revision = '9153e76b1d55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_lord_doctor', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.drop_column('time_lord_doctor')

    # ### end Alembic commands ###
