"""Add Tournament and TournamentParticipant models

Revision ID: 786fcb4a0387
Revises: 283b04784a3c
Create Date: 2025-05-02 16:57:01.511674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '786fcb4a0387'
down_revision = '283b04784a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pairing_system', sa.String(length=30), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournaments_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_organizer_id'), ['organizer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournaments_status'), ['status'], unique=False)

    op.create_table('tournament_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tournament_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('dropped', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_user')
    )
    with op.batch_alter_table('tournament_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tournament_participants_dropped'), ['dropped'], unique=False)
        batch_op.create_index(batch_op.f('ix_tournament_participants_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tournament_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournament_participants_is_active'))
        batch_op.drop_index(batch_op.f('ix_tournament_participants_dropped'))

    op.drop_table('tournament_participants')
    with op.batch_alter_table('tournaments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tournaments_status'))
        batch_op.drop_index(batch_op.f('ix_tournaments_organizer_id'))
        batch_op.drop_index(batch_op.f('ix_tournaments_name'))
        batch_op.drop_index(batch_op.f('ix_tournaments_is_active'))
        batch_op.drop_index(batch_op.f('ix_tournaments_event_date'))

    op.drop_table('tournaments')
    # ### end Alembic commands ###
