"""Add unique constraint to deck_id in CommanderDeck and define relationship

Revision ID: 79bc8bbe0474
Revises: ee82d1b84926
Create Date: 2025-07-17 16:16:00.766550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79bc8bbe0474'
down_revision = 'ee82d1b84926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'commander_decks', ['deck_id'])
    op.create_foreign_key(None, 'commander_decks', 'commanders', ['associated_commander_id'], ['id'])
    op.drop_column('commander_decks', 'relationship_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commander_decks', sa.Column('relationship_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'commander_decks', type_='foreignkey')
    op.drop_constraint(None, 'commander_decks', type_='unique')
    # ### end Alembic commands ###
