"""Se agregan las columnas associated_commander_id y relationship_type al modelo CommanderDeck 

Revision ID: 8ae36c3f7f70
Revises: 3e34bb0d2f8f
Create Date: 2025-03-20 15:53:10.178660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae36c3f7f70'
down_revision = '3e34bb0d2f8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commander_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_commander_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('relationship_type', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'commanders', ['associated_commander_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commander_decks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('relationship_type')
        batch_op.drop_column('associated_commander_id')

    # ### end Alembic commands ###
