"""Renombrar set_name a set_code

Revision ID: 9153e76b1d55
Revises: dcb640860bfd
Create Date: 2025-03-20 11:25:47.541152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9153e76b1d55'
down_revision = 'dcb640860bfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_code', sa.String(), nullable=True))
        batch_op.drop_column('set')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('set_code')

    # ### end Alembic commands ###
