"""Commander now adds choose_a_background column

Revision ID: cc313996ce7d
Revises: e3967e3ac80a
Create Date: 2025-03-21 15:31:03.854847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc313996ce7d'
down_revision = 'e3967e3ac80a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choose_a_background', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.drop_column('choose_a_background')

    # ### end Alembic commands ###
