"""Update logged match

Revision ID: cd5a1428ef55
Revises: e5dd3fb24dc8
Create Date: 2025-06-04 17:38:35.359880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5a1428ef55'
down_revision = 'e5dd3fb24dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('commander_at_seat1_id', sa.Integer(), nullable=True))
    op.add_column('logged_matches', sa.Column('commander_at_seat2_id', sa.Integer(), nullable=True))
    op.add_column('logged_matches', sa.Column('commander_at_seat3_id', sa.Integer(), nullable=True))
    op.add_column('logged_matches', sa.Column('commander_at_seat4_id', sa.Integer(), nullable=True))
    op.drop_constraint('logged_matches_opponent1_commander_id_fkey', 'logged_matches', type_='foreignkey')
    op.drop_constraint('logged_matches_opponent3_commander_id_fkey', 'logged_matches', type_='foreignkey')
    op.drop_constraint('logged_matches_opponent2_commander_id_fkey', 'logged_matches', type_='foreignkey')
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['commander_at_seat1_id'], ['id'])
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['commander_at_seat4_id'], ['id'])
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['commander_at_seat2_id'], ['id'])
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['commander_at_seat3_id'], ['id'])
    op.drop_column('logged_matches', 'opponent1_commander_id')
    op.drop_column('logged_matches', 'opponent2_commander_id')
    op.drop_column('logged_matches', 'opponent3_commander_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('opponent3_commander_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('opponent2_commander_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('opponent1_commander_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.create_foreign_key('logged_matches_opponent2_commander_id_fkey', 'logged_matches', 'commanders', ['opponent2_commander_id'], ['id'])
    op.create_foreign_key('logged_matches_opponent3_commander_id_fkey', 'logged_matches', 'commanders', ['opponent3_commander_id'], ['id'])
    op.create_foreign_key('logged_matches_opponent1_commander_id_fkey', 'logged_matches', 'commanders', ['opponent1_commander_id'], ['id'])
    op.drop_column('logged_matches', 'commander_at_seat4_id')
    op.drop_column('logged_matches', 'commander_at_seat3_id')
    op.drop_column('logged_matches', 'commander_at_seat2_id')
    op.drop_column('logged_matches', 'commander_at_seat1_id')
    # ### end Alembic commands ###
