"""Renombrar set_name a set, añadir flavor_name y asegurar power/toughness/loyalty

Revision ID: dcb640860bfd
Revises: 689ddf931e21
Create Date: 2025-03-20 11:24:49.075755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb640860bfd'
down_revision = '689ddf931e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flavor_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('set', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('partner', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('background', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('friends_forever', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('doctor_companion', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('art_crop', sa.String(), nullable=True))
        batch_op.drop_column('set_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commanders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('art_crop')
        batch_op.drop_column('doctor_companion')
        batch_op.drop_column('friends_forever')
        batch_op.drop_column('background')
        batch_op.drop_column('partner')
        batch_op.drop_column('set')
        batch_op.drop_column('flavor_name')

    # ### end Alembic commands ###
