"""Change oponent commanders field

Revision ID: e5dd3fb24dc8
Revises: f802e688d6ea
Create Date: 2025-06-04 17:21:52.607533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5dd3fb24dc8'
down_revision = 'f802e688d6ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('opponent1_commander_id', sa.Integer(), nullable=True))
    op.add_column('logged_matches', sa.Column('opponent2_commander_id', sa.Integer(), nullable=True))
    op.add_column('logged_matches', sa.Column('opponent3_commander_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['opponent2_commander_id'], ['id'])
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['opponent1_commander_id'], ['id'])
    op.create_foreign_key(None, 'logged_matches', 'commanders', ['opponent3_commander_id'], ['id'])
    op.drop_column('logged_matches', 'opponent1_commander')
    op.drop_column('logged_matches', 'opponent3_commander')
    op.drop_column('logged_matches', 'opponent2_commander')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('opponent2_commander', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('opponent3_commander', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('logged_matches', sa.Column('opponent1_commander', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.drop_constraint(None, 'logged_matches', type_='foreignkey')
    op.drop_column('logged_matches', 'opponent3_commander_id')
    op.drop_column('logged_matches', 'opponent2_commander_id')
    op.drop_column('logged_matches', 'opponent1_commander_id')
    # ### end Alembic commands ###
