"""Add cmc column to Commander model

Revision ID: ee82d1b84926
Revises: 1ec50e376fbe
Create Date: 2025-07-15 15:45:35.158128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee82d1b84926'
down_revision = '1ec50e376fbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commanders', sa.Column('cmc', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commanders', 'cmc')
    # ### end Alembic commands ###
