"""Add updated_at to Tournament model

Revision ID: ef2266fba4d1
Revises: e0e70a397868
Create Date: 2025-05-13 12:04:46.251673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2266fba4d1'
down_revision = 'e0e70a397868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('logged_matches', 'logger_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logged_matches', 'deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_matches_is_active', table_name='logged_matches')
    op.create_index(op.f('ix_logged_matches_is_active'), 'logged_matches', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logged_matches_is_active'), table_name='logged_matches')
    op.create_index('ix_matches_is_active', 'logged_matches', ['is_active'], unique=False)
    op.alter_column('logged_matches', 'deck_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logged_matches', 'logger_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
