"""Fix foreign key constraint name

Revision ID: f2eb62c4fa46
Revises: 8ae36c3f7f70
Create Date: 2025-03-20 15:57:03.034425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2eb62c4fa46'
down_revision = '8ae36c3f7f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commander_decks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('associated_commander_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('relationship_type', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_associated_commander', 'commanders', ['associated_commander_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commander_decks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_associated_commander', type_='foreignkey')
        batch_op.drop_column('relationship_type')
        batch_op.drop_column('associated_commander_id')

    # ### end Alembic commands ###
