"""Add mulligans and opponent commanders to LoggedMatch

Revision ID: f802e688d6ea
Revises: 88ac1a3b8000
Create Date: 2025-06-04 16:49:27.469276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f802e688d6ea'
down_revision = '88ac1a3b8000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('player_mulligans', sa.Integer(), nullable=True))
    op.add_column('logged_matches', sa.Column('opponent1_commander', sa.String(length=255), nullable=True))
    op.add_column('logged_matches', sa.Column('opponent2_commander', sa.String(length=255), nullable=True))
    op.add_column('logged_matches', sa.Column('opponent3_commander', sa.String(length=255), nullable=True))
    op.add_column('logged_matches', sa.Column('pod_notes', sa.Text(), nullable=True))
    op.alter_column('logged_matches', 'logger_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logged_matches', 'deck_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('logged_matches', 'player_position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('logged_matches', 'opponent_description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logged_matches', sa.Column('opponent_description', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('logged_matches', 'player_position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logged_matches', 'deck_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('logged_matches', 'logger_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('logged_matches', 'pod_notes')
    op.drop_column('logged_matches', 'opponent3_commander')
    op.drop_column('logged_matches', 'opponent2_commander')
    op.drop_column('logged_matches', 'opponent1_commander')
    op.drop_column('logged_matches', 'player_mulligans')
    # ### end Alembic commands ###
